### ISSUE TITLE
am I doing this right?

### ISSUE THREAD

**Issue by glacierbliss** [KateMMiller/demo_repo#8]
Am I doing this right? I've followed the directions from https://happygitwithr.com/usage-intro.html 

I think the file that I added went straight into the master and everyone else will be able to see it. Is that right?

If I created my own branch and then modified it, then I would need to do a pull request for it to be brought into the master, right?

Is creating my own branch the "proper" way to do edits, or is it ok to do what I did?

**Comment by johnpauls** [comment]
I can see the new file you added so that worked correctly.

As to the "proper" way that depends on the project. If you were modifying a file that lots of folks use, then making a branch and letting people test it first would be best. Everyone would be able to see / load your branch before it was merged in so it would be easy to test.

Seeing as this is a new file in a demo repo I don't think you need to worry about loading it directly to master this time.

**Comment by wright13** [comment]
Agreed. Another nice thing about creating a separate branch is that it's easy for people to give you feedback through your pull request.
I think I found a fix for your last example so I'll go ahead and make a new branch and a pull request so you can see what that looks like. :)
